export enum Change {
    AwayScoreCurrent = "awayScore.current",
    AwayScoreDisplay = "awayScore.display",
    AwayScoreNormaltime = "awayScore.normaltime",
    AwayScorePeriod1 = "awayScore.period1",
    AwayScorePeriod2 = "awayScore.period2",
    CardsCode = "cardsCode",
    HomeScoreCurrent = "homeScore.current",
    HomeScoreDisplay = "homeScore.display",
    HomeScoreNormaltime = "homeScore.normaltime",
    HomeScorePeriod1 = "homeScore.period1",
    HomeScorePeriod2 = "homeScore.period2",
    StatusCode = "status.code",
    StatusDescription = "status.description",
    StatusType = "status.type",
    TimeCurrentPeriodStart = "time.currentPeriodStart",
    TimeInjuryTime2 = "time.injuryTime2",
    TimePeriod1Start = "time.period1Start",
    TimePeriod2Start = "time.period2Start",
}